### ISSUE TITLE
Weekly Updates on Weekly Digest 

### ISSUE THREAD

**Issue by abhijeetps** [probot/weekly-digest#2]
Hey all! 👋 

I am Abhijeet Singh. A pre-final year CSE undergrad at IIIT Trichy, India.

This April, I got selected asStudent Developer at Probot in Google Summer of Code. 😄 
I would like to thanks @bkeepers , @gr2m , @JasonEtco , @wilhelmklopp and the awesome Probot community for giving me this opportunity.

So, this summer, my major task here is to develop a Weekly Digest application for GitHub.

In this locked issue, I will be sharing weekly updates on my progress.

Please feel free to share any ideas, suggestions, updates, etc., by creating an issue for it or discussing about it in #contributors in Slack!

**Comment by aps120797** [comment]
# Week 1 (14th May - 20th May)

![all_about_dinesh](https://user-images.githubusercontent.com/20141002/40292210-7c9015f0-5ce7-11e8-992e-25f6691cf636.jpg)

The official coding period started from 14th July, but due to my unavailability for the first week of coding period, I had started basics of my work during the community bonding period itself.

So far, during the community bonding period and after that, I had two meetings with my mentors @gr2m and @wilhelmklopp. They guided me how should I approach towards building the application and how I should work on it.

During this time, I made some small commits, opened a few PRs and Issues and received initial responses from the mentors. @bkeepers also tweeted a tweet about the features that the users want during the community bonding period and we receive a few responses.

I have created an initial milestone and I am currently working on it. Will be adding new features via adding milestone. @wilhelmklopp shared an interesting idea of using [MoSCoW method](https://en.wikipedia.org/wiki/MoSCoW_method). I will be using it in the future as the project grows.

Stay tuned for the **Week 2** update. 😄

**Comment by aps120797** [comment]
# Week 2 (21st May - 27th May)

This week had been really exciting for me. I now can see where the app is heading to! 🛩 

Here's a summary of my progress made this week:.

## Progress made so far:

-  Added `issues.getForRepo()`, `pullRequests.getAll()`, `issues.create()` and `issues.createLabel()`.
- Added repos.compareCommits() method also, haven't used it in the app 0i0though.
- Created formatted Markdown methods for Contributors, Issues and Pull Requests
- Here's a sample Weekly Digest generated by Weekly Digest app: https://github.com/aps120797/playground/issues/15

## What I am planning to do by next week?
 - Use probot-scheduler in Weekly Digest
 - Pick data only of last week.
 - Other events and their markdowns?

## Future Plans
- GraphQL?

That's all for Week 2. 
Stay tuned for Week 3 updates. 😃

**Comment by aps120797** [comment]
# Week 3 (28th May - 3rd June)
This week, I think I am very near close to release an alpha version of the app. 

Here's my week progress made so far, what I am planning to do by the week end, and future plans(if any).

## Progress made so far

- Implemented  `probot-scheduler`.
- Fixed createLabel
- Able to create a file `.github/weekly-digest.yml`
- Implemented **Most Liked Issue** and **Most Noisy Issue**
- Here's a sample of my this week's progress: https://github.com/aps120797/playground/issues/23

# What I am planning to do by next week?

- Working on @wilhelmklopp idea's of the way how weekly digest will be published
- Configs can be taken added on `.github/weekly-digest.yml`
- Working with dates, will trigger app on Sundays. (Could be changed as needed)

Future Plans
- Planning to release alpha version by this weekend.

That's all for Week 3.
Stay tuned for Week 4 update and Alpha release (🤞 ).

**Comment by aps120797** [comment]
# Week 4 (4th June - 10th June)
This week, I have launched alpha version [v0.1.0](https://github.com/probot/weekly-digest/releases/tag/v0.1.0).
## Progress made so far:
-  Version [v0.1.0](https://github.com/probot/weekly-digest/releases/tag/v0.1.0) released.
-  Added stargazers.
-  Deployed to Glitch. Alpha version ready to be used.
![A Weekly Digest generated by app.](https://user-images.githubusercontent.com/20141002/41304450-d2bc9234-6e8d-11e8-965d-649ed2d04651.gif)

## What I am planning to do by next week?
- Will be monitoring repositories where these apps are installed.
- Working on issues faced by the users using application.
- Fixing bugs. 🐛 
- Release v0.1.1 🤔 

That's all for Week 4.
Stay tuned for Week 5 update. 😄
