### ISSUE TITLE
[Feature Suggestion] Provide links to search all the past weekly digest issue and the last weekly digest issue

### ISSUE THREAD

**Issue by itaditya** [probot/weekly-digest#34]
Hi, it may be helpful for the community to go through multiple past weekly digests. Another usecase is that someone may want to check the latest weekly digest.

This feature can be easily made by providing a link in the weekly-digest issue to the issue page with the following search queries-

For last weekly-digest - `is:open is:issue author:app/weekly-digest-beta`
For all weekly-digests - `is:issue author:app/weekly-digest-beta`

**Comment by aps120797** [comment]
That's a really nice Idea @itaditya! 
I think I will be implementing it in the next version.
Also, I think, instead of using `author` field, I will use `label` field and make it something like:

For last weekly-digest - `is:open is:issue label:weekly-digest`
For all weekly-digests - `is:issue label:weekly-digest`

This will enable users to remove weekly digests, if the users don't want 'a particular weekly-digest' to be shown in the search issues.
Let me know what you think. 😄

**Comment by itaditya** [comment]
@aps120797 this is much better :+1:

**Comment by abhijeetps** [comment]
This feature has been implemented. Thanks @itaditya for the suggestion. 😄

**Comment by itaditya** [comment]
For showcase, you can put a link of a weekly digest here
